package co.com.home.misiontic2022.view;

import co.com.home.misiontic2022.controller.ReportesController;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class ReportesViewGUI extends javax.swing.JFrame {

    private ReportesController reportesController;

    /**
     * Creates new form ReportesViewGUI
     */
    public ReportesViewGUI() {
        initComponents();
        reportesController = new ReportesController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorConsultas = new javax.swing.JTabbedPane();
        tabProyectoPorBanco = new javax.swing.JPanel();
        panelProyectoPorBanco = new javax.swing.JPanel();
        labelBanco = new javax.swing.JLabel();
        textBanco = new javax.swing.JTextField();
        btnConsulta1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProyectoPorBanco = new javax.swing.JTable();
        tabPagadoPorProyecto = new javax.swing.JPanel();
        panelPagadoPorProyecto = new javax.swing.JPanel();
        labelLimite = new javax.swing.JLabel();
        textLimite = new javax.swing.JTextField();
        btnConsulta2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPagadoPorProyecto = new javax.swing.JTable();
        tabComprasDeLider = new javax.swing.JPanel();
        panelComprasDeLider = new javax.swing.JPanel();
        btnConsulta3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaComprasDeLider = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reto 5");
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        tabProyectoPorBanco.setLayout(new java.awt.BorderLayout());

        panelProyectoPorBanco.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        labelBanco.setText("Banco");
        panelProyectoPorBanco.add(labelBanco);

        textBanco.setColumns(12);        
        panelProyectoPorBanco.add(textBanco);

        btnConsulta1.setText("Consultar");
        btnConsulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsulta1ActionPerformed(evt);
            }
        });
        panelProyectoPorBanco.add(btnConsulta1);

        tabProyectoPorBanco.add(panelProyectoPorBanco, java.awt.BorderLayout.NORTH);

        tablaProyectoPorBanco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Constructora", "Ciudad", "Clasificación", "Estrato", "Líder"
            }
        ));
        tablaProyectoPorBanco.setShowGrid(true);
        jScrollPane1.setViewportView(tablaProyectoPorBanco);

        tabProyectoPorBanco.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        contenedorConsultas.addTab("Proyecto por banco", tabProyectoPorBanco);

        tabPagadoPorProyecto.setLayout(new java.awt.BorderLayout());

        panelPagadoPorProyecto.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        labelLimite.setText("Limite inferior");
        panelPagadoPorProyecto.add(labelLimite);

        textLimite.setColumns(12);
        panelPagadoPorProyecto.add(textLimite);

        btnConsulta2.setText("Consultar");
        btnConsulta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsulta2ActionPerformed(evt);
            }
        });
        panelPagadoPorProyecto.add(btnConsulta2);

        tabPagadoPorProyecto.add(panelPagadoPorProyecto, java.awt.BorderLayout.NORTH);

        tablaPagadoPorProyecto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Proyecto", "Valor"
            }
        ));
        tablaPagadoPorProyecto.setShowGrid(true);
        jScrollPane2.setViewportView(tablaPagadoPorProyecto);

        tabPagadoPorProyecto.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        contenedorConsultas.addTab("Pagado por proyecto", tabPagadoPorProyecto);

        tabComprasDeLider.setLayout(new java.awt.BorderLayout());

        panelComprasDeLider.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnConsulta3.setText("Consultar");
        btnConsulta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsulta3ActionPerformed(evt);
            }
        });
        panelComprasDeLider.add(btnConsulta3);

        tabComprasDeLider.add(panelComprasDeLider, java.awt.BorderLayout.NORTH);

        tablaComprasDeLider.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Líder", "Valor"
            }
        ));
        tablaComprasDeLider.setShowGrid(true);
        jScrollPane3.setViewportView(tablaComprasDeLider);

        tabComprasDeLider.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        contenedorConsultas.addTab("Compras de lider", tabComprasDeLider);

        getContentPane().add(contenedorConsultas, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents    

    private void btnConsulta1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnConsulta1ActionPerformed
        proyectosFinanciadosPorBanco(textBanco.getText().trim());
    }

    private void btnConsulta2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnConsulta2ActionPerformed
        try {
            totalPagadoPorProyectosSuperioresALimite(Double.valueOf(textLimite.getText()));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Limite no válido", getTitle(), JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnConsulta3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnConsulta3ActionPerformed
        lideresQueMenosGastan();
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsulta1;
    private javax.swing.JButton btnConsulta2;
    private javax.swing.JButton btnConsulta3;
    private javax.swing.JTabbedPane contenedorConsultas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelBanco;
    private javax.swing.JLabel labelLimite;
    private javax.swing.JPanel panelComprasDeLider;
    private javax.swing.JPanel panelPagadoPorProyecto;
    private javax.swing.JPanel panelProyectoPorBanco;
    private javax.swing.JPanel tabComprasDeLider;
    private javax.swing.JPanel tabPagadoPorProyecto;
    private javax.swing.JPanel tabProyectoPorBanco;
    private javax.swing.JTable tablaComprasDeLider;
    private javax.swing.JTable tablaPagadoPorProyecto;
    private javax.swing.JTable tablaProyectoPorBanco;
    private javax.swing.JTextField textBanco;
    private javax.swing.JTextField textLimite;
    // End of variables declaration//GEN-END:variables

    public void proyectosFinanciadosPorBanco(String banco) {
        try {
            var respuesta = reportesController.listadoDeProyectoPorBanco(banco);
            var tableModel = new ProyectoBancoTableModel(respuesta);
            tablaProyectoPorBanco.setModel(tableModel);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), getTitle(), JOptionPane.ERROR_MESSAGE);
        }

    }

    public void totalPagadoPorProyectosSuperioresALimite(Double limiteInferior) {
        try {
            var respuesta = reportesController.listadoDePagoPorProyecto(limiteInferior);
            var tableModel = new PagadoPorProyectoTableModel(respuesta);
            tablaPagadoPorProyecto.setModel(tableModel);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), getTitle(), JOptionPane.ERROR_MESSAGE);
        }

    }

    public void lideresQueMenosGastan() {
        try {
            var respuesta = reportesController.listadoDeComprasDeLider();
            var tableModel = new ComprasDeLiderTableModel(respuesta);
            tablaComprasDeLider.setModel(tableModel);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), getTitle(), JOptionPane.ERROR_MESSAGE);
        }

    }
}
